apiVersion: v1
kind: Namespace
metadata:
  name:  site
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-nginx
  namespace: site
data:
  NGINX_PORT: "8000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: file-nginx
  namespace: site
data:
  default.conf.template: |
    server {
      listen       ${NGINX_PORT};
      listen  [::]:${NGINX_PORT};
      server_name  localhost;

      #access_log  /var/log/nginx/host.access.log  main;

      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }

      #error_page  404              /404.html;

      # redirect server error pages to the static page /50x.html
      #
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }

      # proxy the PHP scripts to Apache listening on 127.0.0.1:80
      #
      #location ~ \.php$ {
      #    proxy_pass   http://127.0.0.1;
      #}

      # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
      #
      #location ~ \.php$ {
      #    root           html;
      #    fastcgi_pass   127.0.0.1:9000;
      #    fastcgi_index  index.php;
      #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
      #    include        fastcgi_params;
      #}

      # deny access to .htaccess files, if Apache's document root
      # concurs with nginx's one
      #
      #location ~ /\.ht {
      #    deny  all;
      #}
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: site
  labels:
    name: nginx
spec:
  volumes:
    - name: nginx-conf
      configMap:
        name: file-nginx
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    envFrom:
      - configMapRef:
          name: env-nginx
    # env: # Alternativa
    #   - name: NGINX_PORT
    #     value: "8000"
    volumeMounts:
      - name:  nginx-conf
        mountPath:  /etc/nginx/templates/

