apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: site
spec:
  replicas: 3
  selector:
    matchLabels:
      app:  nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name:  nginx
spec:
  selector:
    app:  nginx
  type:  NodePort
  ports:
  - name:  nginx
    port:  80
    targetPort:  80