apiVersion: batch/v1
kind: Job
metadata:
  name: test
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
      - name: hello-world
        image: ubuntu:latest
        command: ["bash",  "-c", "echo hello!"]
      restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-cron
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 80
      template:
        spec:
          containers:
          - name: hello-world
            image: ubuntu:latest
            command: ["bash",  "-c", "echo hello!"]
          restartPolicy: Never