apiVersion: v1
kind: Namespace
metadata:
  name:  site
---
kind: Service
apiVersion: v1
metadata:
  name:  n8n
  namespace: site
spec:
  selector:
    app:  n8n
  type:  LoadBalancer
  ports:
  - name:  n8n
    port:  5678
    targetPort:  5678
---
apiVersion: v1
kind: Pod
metadata:
  name: n8n
  namespace: site
  labels:
    name: n8n
spec:
  containers:
  - name: n8n
    image: n8nio/n8n:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5678
